[package]
name = "kaleidoscope"
version = "0.2.0"
license = "MIT"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>", "Alekos Filini <alekos.filini@gmail.com>"]
description = "Command-line bitcoin and RGB wallet"
keywords = ["bitcoin", "lightning", "layer-2", "crypto", "rgb"]
readme = "README.md"
edition = "2018"

[dependencies]
bitcoin-wallet = { git = "https://github.com/rgb-org/rust-wallet", branch = "staging" }
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"
rpassword = "~4.0"
dotenv = "~0.15"
shellexpand = "~2.0"
clap = { git = "https://github.com/clap-rs/clap.git" }
regex = "~1.3"
chrono = "~0.4"
derive_wrapper = "0.1.5"
async-trait = "~0.1"
num-traits = "~0.2.11"
num-derive = "~0.3.0"
rand = "~0.7"
log = { version = "~0.4", features = ["max_level_trace", "release_max_level_debug"] }
env_logger = "~0.7"
diesel = { version = "~1.4", features = ["sqlite", "uuid", "numeric", "chrono"] }
tokio = { version = "~0.2", features = ["full"] }
futures = "~0.3"
zmq = "~0.9"
electrum-client = { git = "https://github.com/lnp-bp/rust-electrum-client", branch = "staging" }

[dependencies.lnpbp]
git = "https://github.com/lnp-bp/rust-lnpbp"
branch = "develop"
features = ["all"]
